In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import matplotlib as mpl
import seaborn as sns
import glob
import warnings
warnings.filterwarnings('ignore')
sns.set(rc={"figure.dpi":1200})
sns.set_context('notebook')
sns.set_style("ticks")
mpl.style.use('default')
mpl.rcParams['axes.linewidth'] = 7 #set the value globally
mpl.rcParams['xtick.major.size'] = 20
mpl.rcParams['xtick.major.width'] = 7
mpl.rcParams['xtick.minor.size'] = 10
mpl.rcParams['xtick.minor.width'] = 7
mpl.rcParams['ytick.major.size'] = 20
mpl.rcParams['ytick.major.width'] = 7
mpl.rcParams['ytick.labelsize'] = 50
mpl.rcParams['xtick.labelsize'] = 50
mpl.rcParams['ytick.minor.size'] = 10
mpl.rcParams['ytick.minor.width'] = 7
mpl.rcParams['font.size'] = 55
mpl.rcParams['font.sans-serif']='Arial'

In [14]:
###IMPORT DATAFRAMES AND FILTER MAIN LIVE-CELL DATAFRAME
df = pd.read_csv('STALLER_MANUSCRIPT_HIF1A_CITED2_MASTER.csv',index_col=0)
df = df[(df['D std']<4000)]
df = df[(df['A std']<4000)]
df = df[(df['area']<10000)]
df = df[(df['log directA']>3.1)]
sim=pd.read_csv('combined_CIDER_Ree_wGene.csv',index_col=0)

In [7]:
#select for HIF and CITED2
HIF = df[df['protein'] != 'CITED2']
CITED2 = df[df['protein'] != 'HIF1A']

In [11]:
# Step 1: Group by 'well' and 'mut name', then calculate the median for each group
medians_by_well = HIF.groupby(['well', 'mut name'])['Ef'].median().reset_index(name='median_Ef')

# Step 2: Calculate the average and standard deviation of these medians for each 'mut name'
HIF_stats = medians_by_well.groupby('mut name')['median_Ef'].agg(
    avg_median='mean',
    std_dev_median='std'
).reset_index()

print(HIF_stats)

# Step 1: Group by 'well' and 'mut name', then calculate the median for each group
medians_by_well = CITED2.groupby(['well', 'mut name'])['Ef'].median().reset_index(name='median_Ef')

# Step 2: Calculate the average and standard deviation of these medians for each 'mut name'
CITED2_stats = medians_by_well.groupby('mut name')['median_Ef'].agg(
    avg_median='mean',
    std_dev_median='std'
).reset_index()

print(CITED2_stats)

  mut name  avg_median  std_dev_median
0     MA>W    0.550599        0.008102
1     NQ>W    0.534472        0.011276
2     RK>D    0.402201        0.009229
3     RK>E    0.423864        0.005103
4       WT    0.450021        0.005151
        mut name  avg_median  std_dev_median
0      ED>A0to20    0.322848        0.059180
1          FML>A    0.481063        0.008786
2            L>F    0.570753        0.006982
3            L>W    0.610975        0.016607
4  RK>Amut20to39    0.582256        0.014517
5           RK>E    0.571767        0.007862
6             WT    0.592293        0.014540

In [15]:
sim

,Unnamed: 0,fasta_header,lengths,end_to_end_distance,Ree,sequence,Gene
0,0,Hif1-AD2_46 NQ>W,46,35.988096,3.598809554,RLLGWSMDES\nGLPWLTSYDC\nEVWAPIWGSR\nWLLWGEELLR...,Hif1-AD2_46
1,1,Hif1-AD2_46 MA>W,46,43.197128,4.319712832,RLLGQSWDES\nGLPQLTSYDC\nEVNWPIQGSR\nNLLQGEELLR...,Hif1-AD2_46
2,2,Hif1-AD2_46 WT,46,46.696221,4.669622059,RLLGQSMDES\nGLPQLTSYDC\nEVNAPIQGSR\nNLLQGEELLR...,Hif1-AD2_46
3,3,Hif1-AD2_46 supercharge6,46,49.350452,4.935045168,ELLGQSMDES\nGLPQLTSYDC\nEVNAPIQGSE\nFLLQGEELLD...,Hif1-AD2_46
4,4,Hif1-AD2_46 RK>D,46,49.619403,4.961940316,DLLGQSMDES\nGLPQLTSYDC\nEVNAPIQGSD\nNLLQGEELLD...,Hif1-AD2_46
...,...,...,...,...,...,...,...
181,88,OTX_221-270_H230L,50,47.470461,4.747046078,PMGTNAVTSL\nLNQSPASLST\nQGYGASSLGF\nNSTTDCLDYK...,OTX
182,89,OTX_221-270_G250E,50,47.546966,4.754696574,PMGTNAVTSH\nLNQSPASLST\nQGYGASSLGE\nNSTTDCLDYK...,OTX
183,90,OTX_221-270_D261G,50,46.574904,4.657490431,PMGTNAVTSH\nLNQSPASLST\nQGYGASSLGF\nNSTTDCLDYK...,OTX
184,91,OTX_240-289_D261G,50,42.871680,4.28716799,TQGYGASSLG\nFNSTTDCLDY\nKGQTASWKLN\nFNADCLDYKD...,OTX
185,92,OTX_240-289_S283L,50,43.247977,4.324797708,TQGYGASSLG\nFNSTTDCLDY\nKDQTASWKLN\nFNADCLDYKD...,OTX

In [16]:
# Combine the mappings into one
mapping = {
    1: 'NQ>W', 2: 'MA>W', 3: 'WT', 4: 'RK>E', 5: 'RK>D', 24: 'GS24',
    6: 'ED>A0to20', 7: 'FML>A', 8: 'L>F', 9: 'L>W', 10: 'WT', 11: 'RK>E',
    12: 'RK>Amut20to39'
}

# Map the 'Unnamed: 0' column to the new 'mut name' column
sim['mut name'] = sim['Unnamed: 0'].map(mapping)